# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE_LINTERS:
  - PYTHON_PYLINT # Optional import noise; not used here
  - PYTHON_PYRIGHT # Shows errors that are not relevant in this context
  - COPYPASTE_JSCPD # Repeated scaffolding acceptable
  - REPOSITORY_KICS # Security scan disabled for now
  - YAML_YAMLLINT # No YAML files to lint
  - SPELL_CSPELL # Handled sepetately in GitHub Actions
  - PYTHON_MYPY # Not worth effort to make work will fix it eventually

PYTHON_FLAKE8_CONFIG_FILE: .flake8
PYTHON_BANDIT_CONFIG_FILE: .bandit
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdown lint.json

SHOW_ELAPSED_TIME: true
OUTPUT_FORMAT: text
