# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE_LINTERS:
  - PYTHON_PYLINT # Optional import noise; not used here
  - COPYPASTE_JSCPD # Repeated scaffolding acceptable
  - REPOSITORY_KICS # Security scan disabled for now

PYTHON_FLAKE8_CONFIG_FILE: .flake8
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
SPELL_CSPELL_CONFIG_FILE: .cspell.json
PYTHON_PYRIGHT_CONFIG_FILE: pyproject.toml

SHOW_ELAPSED_TIME: true
OUTPUT_FORMAT: text
